INSERT INTO PROMOTION (PRODUCT_ID, PROMO_CODE, PROMO_DISCOUNT, PROMO_DESCRIPTION) VALUES (1L, 'TEST', '10%', 'test promo');
INSERT INTO PROMOTION (PRODUCT_ID, PROMO_CODE, PROMO_DISCOUNT, PROMO_DESCRIPTION) VALUES (2L, 'TEST1', '20%', 'test promo1');
INSERT INTO PROMOTION (PRODUCT_ID, PROMO_CODE, PROMO_DISCOUNT, PROMO_DESCRIPTION) VALUES (3L, 'TEST3', '5%', 'test promo3');
commit;