DROP TABLE IF EXISTS PROMOTION;

CREATE TABLE PROMOTION (
       PROMOTION_ID INT auto_increment PRIMARY KEY ,
       PRODUCT_ID INT NOT NULL ,
       PROMO_CODE VARCHAR(250) NOT NULL,
       PROMO_DISCOUNT VARCHAR(250) NOT NULL,
       PROMO_DESCRIPTION VARCHAR(250) NOT NULL
);